/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;
import java.sql.Connection;
import InterfazV2.menuPrincipal;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.sql.ResultSet;
import util.Conexion;
/**
 *
 * @author sergio
 */
public class PanelLogin extends javax.swing.JFrame {
    ArrayList users;
    Connection miConexion;
    /**
     * Creates new form PanelLogin
     */
    public PanelLogin() {
        initComponents();
        miConexion = new Conexion("localhost","3306","zoo","zoologico","pepe").makeConnect();
        users = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelIniciarSesion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelPass = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabelCarpincho = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jLabelCrearCuenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.png"))); // NOI18N
        jPanel1.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabelIniciarSesion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelIniciarSesion.setForeground(new java.awt.Color(51, 51, 51));
        jLabelIniciarSesion.setText("Iniciar sesión");
        jPanel1.add(jLabelIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 400));
        jPanel2.setLayout(new java.awt.GridLayout(4, 1));

        jLabelNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(0, 153, 51));
        jLabelNombre.setText("Nombre:");
        jPanel2.add(jLabelNombre);

        jTextFieldNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNombre.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 36), new java.awt.Color(0, 153, 51))); // NOI18N
        jTextFieldNombre.setMargin(new java.awt.Insets(0, 0, 1, 0));
        jPanel2.add(jTextFieldNombre);

        jLabelPass.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelPass.setForeground(new java.awt.Color(0, 153, 51));
        jLabelPass.setText("Contraseña");
        jPanel2.add(jLabelPass);

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(jPasswordField1);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 360, -1));

        jLabelCarpincho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carpincho.jpg"))); // NOI18N
        jPanel1.add(jLabelCarpincho, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, -1));

        jButtonLogin.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("Iniciar sesión");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, -1, -1));

        jLabelCrearCuenta.setForeground(new java.awt.Color(0, 153, 51));
        jLabelCrearCuenta.setText("Crear cuenta");
        jLabelCrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearCuenta(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelCrearCuentaMousePressed(evt);
            }
        });
        jPanel1.add(jLabelCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 580, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 863, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 180, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        String nombre = jTextFieldNombre.getText().trim();
        char[] pass = jPasswordField1.getPassword();
        String passwd = new String (pass);
        if(nombre.equals("")){
            JOptionPane.showMessageDialog(null, "Introduce el nombre");
        } 
        else if(pass.equals("")){
            JOptionPane.showMessageDialog(null, "La contraseña está vacía");
        }
        else{
            ResultSet rs1 =util.Conexion.comprobarDatos("SELECT * FROM admin WHERE USER = '"+nombre+"' AND pass ='"+passwd+"'",miConexion);
            System.out.println(rs1);
            if(rs1==null){
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos");
            }
            else{
                JOptionPane.showMessageDialog(null, "Usuario correcto");
                menuPrincipal mp = new menuPrincipal();
                mp.setVisible(true);
                this.setVisible(false);
                
            }
            
            
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void crearCuenta(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearCuenta
        Login.Register r = new Login.Register();
        r.setVisible(true);
        jLabelCrearCuenta.setForeground(Color.decode("#009933"));
    }//GEN-LAST:event_crearCuenta

    private void jLabelCrearCuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCrearCuentaMousePressed
        jLabelCrearCuenta.setForeground(Color.decode("#FF6666"));
    }//GEN-LAST:event_jLabelCrearCuentaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabelCarpincho;
    private javax.swing.JLabel jLabelCrearCuenta;
    private javax.swing.JLabel jLabelIniciarSesion;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
