/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import util.Conexion;
import util.utilities;
import zoo.Especialidad;

/**
 *
 * @author Sergio
 */
public class Register extends javax.swing.JFrame {
    ArrayList users;
    ArrayList<Especialidad> especialidades;
    Connection miConexion;

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        miConexion = new Conexion("localhost","3306","zoo","zoologico","pepe").makeConnect();
        users = new ArrayList();
        especialidades = new ArrayList<Especialidad>();
        //Rellenamos la caja de especialidades
            try{
                String consultaEspecialidad = "SELECT * FROM especialidad";
                DefaultComboBoxModel model = new DefaultComboBoxModel();
                ResultSet rsEspecialidad = util.Conexion.getSelect(consultaEspecialidad,miConexion);
                while (rsEspecialidad.next()){
                    Especialidad esp = new Especialidad(rsEspecialidad.getInt(1),rsEspecialidad.getString(2));
                    especialidades.add(esp);
                    model.addElement(esp);
                    //System.out.println(rsEspecialidad.getString(1)+rsEspecialidad.getString(2));
                }
                jComboBoxEspecialidad.setModel(model);
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        capa0 = new javax.swing.JPanel();
        LRegister = new javax.swing.JLabel();
        JLNombre = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        JLSalario = new javax.swing.JLabel();
        jTFTel = new javax.swing.JTextField();
        JLEspecialidad = new javax.swing.JLabel();
        JLNum1 = new javax.swing.JLabel();
        jComboBoxEspecialidad = new javax.swing.JComboBox<>();
        JLApellidos = new javax.swing.JLabel();
        jTFApe = new javax.swing.JTextField();
        jSSalario = new javax.swing.JSpinner();
        jTFUser = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        JLUser = new javax.swing.JLabel();
        JLPass = new javax.swing.JLabel();
        jButtonRegister = new javax.swing.JButton();
        JLNombre1 = new javax.swing.JLabel();
        JLPass1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        capa0.setBackground(new java.awt.Color(255, 255, 255));
        capa0.setPreferredSize(new java.awt.Dimension(800, 600));
        java.awt.GridBagLayout capa0Layout = new java.awt.GridBagLayout();
        capa0Layout.columnWidths = new int[] {0, 35, 0};
        capa0Layout.rowHeights = new int[] {0, 32, 0, 32, 0, 32, 0, 32, 0, 32, 0, 32, 0, 32, 0, 32, 0};
        capa0.setLayout(capa0Layout);

        LRegister.setBackground(new java.awt.Color(255, 255, 255));
        LRegister.setFont(new java.awt.Font("Freshman", 0, 36)); // NOI18N
        LRegister.setForeground(new java.awt.Color(51, 51, 51));
        LRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LRegister.setText("Registrarse");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        capa0.add(LRegister, gridBagConstraints);

        JLNombre.setFont(new java.awt.Font("Freshman", 0, 18)); // NOI18N
        JLNombre.setForeground(new java.awt.Color(0, 86, 44));
        JLNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLNombre.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        capa0.add(JLNombre, gridBagConstraints);

        jTFNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTFNombre.setFont(new java.awt.Font("Freshman", 0, 18)); // NOI18N
        jTFNombre.setForeground(new java.awt.Color(0, 0, 0));
        jTFNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jTFNombre.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        capa0.add(jTFNombre, gridBagConstraints);

        JLSalario.setFont(new java.awt.Font("Freshman", 0, 18)); // NOI18N
        JLSalario.setForeground(new java.awt.Color(0, 86, 44));
        JLSalario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLSalario.setText("Salario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        capa0.add(JLSalario, gridBagConstraints);

        jTFTel.setBackground(new java.awt.Color(255, 255, 255));
        jTFTel.setFont(new java.awt.Font("Freshman", 0, 18)); // NOI18N
        jTFTel.setForeground(new java.awt.Color(0, 0, 0));
        jTFTel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jTFTel.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        capa0.add(jTFTel, gridBagConstraints);

        JLEspecialidad.setFont(new java.awt.Font("Freshman", 0, 18)); // NOI18N
        JLEspecialidad.setForeground(new java.awt.Color(0, 86, 44));
        JLEspecialidad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLEspecialidad.setText("Especialidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        capa0.add(JLEspecialidad, gridBagConstraints);

        JLNum1.setFont(new java.awt.Font("Freshman", 0, 18)); // NOI18N
        JLNum1.setForeground(new java.awt.Color(0, 86, 44));
        JLNum1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLNum1.setText("Telefono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        capa0.add(JLNum1, gridBagConstraints);

        jComboBoxEspecialidad.setFont(new java.awt.Font("Freshman", 0, 18)); // NOI18N
        jComboBoxEspecialidad.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        capa0.add(jComboBoxEspecialidad, gridBagConstraints);

        JLApellidos.setFont(new java.awt.Font("Freshman", 0, 18)); // NOI18N
        JLApellidos.setForeground(new java.awt.Color(0, 86, 44));
        JLApellidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLApellidos.setText("Apellidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        capa0.add(JLApellidos, gridBagConstraints);

        jTFApe.setBackground(new java.awt.Color(255, 255, 255));
        jTFApe.setFont(new java.awt.Font("Freshman", 0, 18)); // NOI18N
        jTFApe.setForeground(new java.awt.Color(0, 0, 0));
        jTFApe.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jTFApe.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        capa0.add(jTFApe, gridBagConstraints);

        jSSalario.setFont(new java.awt.Font("Freshman", 0, 18)); // NOI18N
        jSSalario.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));
        jSSalario.setPreferredSize(new java.awt.Dimension(100, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        capa0.add(jSSalario, gridBagConstraints);

        jTFUser.setBackground(new java.awt.Color(255, 255, 255));
        jTFUser.setFont(new java.awt.Font("Freshman", 0, 18)); // NOI18N
        jTFUser.setForeground(new java.awt.Color(0, 0, 0));
        jTFUser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jTFUser.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        capa0.add(jTFUser, gridBagConstraints);

        jPasswordField1.setFont(new java.awt.Font("Freshman", 0, 18)); // NOI18N
        jPasswordField1.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        capa0.add(jPasswordField1, gridBagConstraints);

        JLUser.setFont(new java.awt.Font("Freshman", 0, 18)); // NOI18N
        JLUser.setForeground(new java.awt.Color(0, 86, 44));
        JLUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLUser.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        capa0.add(JLUser, gridBagConstraints);

        JLPass.setFont(new java.awt.Font("Freshman", 0, 18)); // NOI18N
        JLPass.setForeground(new java.awt.Color(0, 86, 44));
        JLPass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLPass.setText("Contrasena");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        capa0.add(JLPass, gridBagConstraints);

        jButtonRegister.setFont(new java.awt.Font("Freshman", 0, 18)); // NOI18N
        jButtonRegister.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRegister.setText("Registrar");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 3;
        capa0.add(jButtonRegister, gridBagConstraints);

        JLNombre1.setFont(new java.awt.Font("Freshman", 0, 18)); // NOI18N
        JLNombre1.setForeground(new java.awt.Color(0, 153, 51));
        JLNombre1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLNombre1.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        capa0.add(JLNombre1, gridBagConstraints);

        JLPass1.setFont(new java.awt.Font("Freshman", 0, 18)); // NOI18N
        JLPass1.setForeground(new java.awt.Color(0, 153, 51));
        JLPass1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLPass1.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        capa0.add(JLPass1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(capa0, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(capa0, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        //Recogemos los datos de los campos de texto
        String nombre = jTFNombre.getText();
        String ape = jTFApe.getText();
        String user = jTFUser.getText();
        char[] pass = jPasswordField1.getPassword();
        String passwd = utilities.getEncryptedPass(new String (pass));
        float salario = (float)jSSalario.getValue();
        String num = jTFTel.getText();
        Especialidad esp = new Especialidad((Especialidad)jComboBoxEspecialidad.getSelectedItem());
        int especialidad = esp.getId();
        //Hacemos las comprobaciones necesarias
        //Comprobamos que el nombre no esté vacío
        if(nombre.equals("")){
            JOptionPane.showMessageDialog(null, "Introduce el nombre");
        }
        //Comprobamos que el apellido no esté vacío
        else if(ape.equals("")){
            JOptionPane.showMessageDialog(null, "Introduce el apellido");
        }
        //Comprobamos que el salario no sea 0
        else if(salario==0){
            JOptionPane.showMessageDialog(null, "El salario no puede ser 0");
        }
        //Comprobamos que el número de teléfono no esté vacío
        else if(num.equals("")){
            JOptionPane.showMessageDialog(null, "Introduce el número de teléfono");
        }
        //Comprobamos que el número de teléfono tenga 9 caracteres
        else if(num.length()!=9){
            JOptionPane.showMessageDialog(null, "Introduce correctamente número de teléfono");
        }
        //Comprobamos que el nombre de usuario no esté vacío
        else if(user.equals("")){
            JOptionPane.showMessageDialog(null, "Introduce el nombre de usuario");
        }
        //Comprobamos que la contraseña no esté vacía
        else if(passwd.equals("")){
            JOptionPane.showMessageDialog(null, "Introduce la contraseña");
        }
        //admin es el nombre del usuario admin, por lo tanto no es válido
        else if(user.equals("admin")){
            JOptionPane.showMessageDialog(null, "Nombre de usuario no válido");
        }
        //admin es la contraseña del usuario admin, por lo tanto no es válida
        else if(passwd.equals("admin")){
            JOptionPane.showMessageDialog(null, "Contraseña válida");
        }
        else{
            try {
                //Comprobamos que el cuidador no existe (al menos con el mismo nombre, apellido y telefono)
                String consulta = "SELECT * FROM persona,cuidador WHERE nombre='"+nombre+"' AND apellido='"+ape+"' AND TELEFONO ='"+num+"'AND CUIDADOR.ID_ESP='"+esp.getId()+"'";
                ResultSet rs1 = util.Conexion.comprobarDatos(consulta,miConexion);
                //System.out.println(consulta);
                if(rs1==null){
                    String valitateUser = "SELECT * FROM CUIDADOR WHERE user='"+user+"'";
                    ResultSet rsUser = util.Conexion.comprobarDatos(consulta,miConexion);
                    if(rsUser==null){
                        miConexion.setAutoCommit(false);
                        LocalDateTime dateTime = LocalDateTime.now();
                        String currentTimeStamp = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.0").format(dateTime);
                        ResultSet rs = util.Conexion.getSelect("Select * from persona",miConexion);
                        //Irse a la ultima linea de la tabla persona
                        rs.moveToInsertRow();
                        rs.updateString("nombre",nombre);
                        rs.updateString("apellido",ape);
                        rs.updateFloat("salario",salario);
                        rs.updateString("telefono", num);
                        rs.insertRow();
                        ResultSet rs2 = util.Conexion.getSelect("Select * from cuidador",miConexion);
                        ResultSet getId= util.Conexion.getSelect("SELECT AUTO_INCREMENT FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='ZOO' AND TABLE_NAME='PERSONA'",miConexion);
                        System.out.println(getId);
                        if(!getId.next()){
                            miConexion.rollback();
                        }
                        else{
                            int idPersona = getId.getInt(1);
                        }
                        //System.out.println(getId.getInt("AUTO_INCREMENT")-1);
                        rs2.moveToInsertRow();
                        rs2.updateInt(1, getId.getInt("AUTO_INCREMENT")-1);
                        rs2.updateInt(2,especialidad);
                        rs2.updateString(3, user);
                        rs2.updateString(4, passwd);
                        rs2.insertRow();
                        ResultSet getId2= util.Conexion.getSelect("SELECT AUTO_INCREMENT FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='ZOO' AND TABLE_NAME='CUIDADOR'",miConexion);
                        if(getId2==null){
                            miConexion.rollback();
                        }
                        else{
                            miConexion.commit();
                        }
                        JOptionPane.showMessageDialog(null, "Cuidador registrado correctamente");
                        jTFNombre.setText("");
                        jTFApe.setText("");
                        jTFTel.setText("");
                        jSSalario.setValue(0);
                        this.setVisible(false);
                    }
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "El nombre de usuario ya existe");
                }
            
        }   catch (SQLException ex) {  
                JOptionPane.showMessageDialog(null, "El nombre de usuario ya existe");
            }  
        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLApellidos;
    private javax.swing.JLabel JLEspecialidad;
    private javax.swing.JLabel JLNombre;
    private javax.swing.JLabel JLNombre1;
    private javax.swing.JLabel JLNum1;
    private javax.swing.JLabel JLPass;
    private javax.swing.JLabel JLPass1;
    private javax.swing.JLabel JLSalario;
    private javax.swing.JLabel JLUser;
    private javax.swing.JLabel LRegister;
    private javax.swing.JPanel capa0;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JComboBox<String> jComboBoxEspecialidad;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSpinner jSSalario;
    private javax.swing.JTextField jTFApe;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFTel;
    private javax.swing.JTextField jTFUser;
    // End of variables declaration//GEN-END:variables
}
