package InterfazV2;

import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Conexion;
import util.TextPrompt;
import zoo.Especialidad;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sergio
 */
public class addCuidadores extends javax.swing.JFrame {
    ArrayList<Especialidad> especialidades;
    Conexion miConexion;
    DefaultTableModel modelo;
    /**
     * Creates new form addEspecialidad
     */
    public addCuidadores() {
        try{
            initComponents();
            //TextPrompt sirve para poner un placeholder en un textfield
            TextPrompt name = new TextPrompt("Jorge", jTFNombreCuidador);
            TextPrompt apellido = new TextPrompt("Sanchez", jTFApe);
            TextPrompt telefono = new TextPrompt("958645234", jTFTel);
            
            especialidades = new ArrayList<Especialidad>();
            miConexion = new Conexion("localhost","3306","zoologico","zoo","pepe");
            //Rellenamos la tabla de animales con los animales de la base de datos
            modelo = (DefaultTableModel) jTablaCuidadores.getModel();
            String consulta = "SELECT ID_PERSONA,persona.NOMBRE,persona.APELLIDO,persona.SALARIO,persona.TELEFONO,especialidad.nombre as ESPECIALIDAD,especialidad.id ,persona.LAST_MOD  FROM persona,especialidad,cuidador WHERE cuidador.id_esp=especialidad.id AND persona.ID_PERSONA=cuidador.id_per ORDER BY persona.ID_PERSONA";
            System.out.println(consulta);
            ResultSet rsTabla = miConexion.getSelect(consulta);
            //System.out.println(miConexion.getSelect(consulta));
            while(rsTabla.next()){
                Especialidad esp = new Especialidad(rsTabla.getInt(7),rsTabla.getString(6));
                modelo.addRow(new Object[] {rsTabla.getInt(1),rsTabla.getString(2),rsTabla.getString(3),rsTabla.getFloat(4),rsTabla.getString(5),esp,rsTabla.getTimestamp(8)});
            }
            //Rellenamos la caja de especialidades
            try{
                String consultaEspecialidad = "SELECT * FROM especialidad";
                DefaultComboBoxModel model = new DefaultComboBoxModel();
                ResultSet rsEspecialidad = miConexion.getSelect(consultaEspecialidad);
                while (rsEspecialidad.next()){
                    Especialidad esp = new Especialidad(rsEspecialidad.getInt(1),rsEspecialidad.getString(2));
                    especialidades.add(esp);
                    model.addElement(esp);
                    //System.out.println(rsEspecialidad.getString(1)+rsEspecialidad.getString(2));
                }
                jComboBoxEspecialidad.setModel(model);
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }
        }
        catch(SQLException ex){
            Logger.getLogger(addCuidadores.class.getName()).log(Level.SEVERE,null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        capa0 = new javax.swing.JPanel();
        addCuidador = new javax.swing.JLabel();
        JLNombre = new javax.swing.JLabel();
        jTFNombreCuidador = new javax.swing.JTextField();
        JLSalario = new javax.swing.JLabel();
        jTFTel = new javax.swing.JTextField();
        JLEspecialidad = new javax.swing.JLabel();
        JLNum1 = new javax.swing.JLabel();
        jComboBoxEspecialidad = new javax.swing.JComboBox<>();
        JLApellidos = new javax.swing.JLabel();
        jTFApe = new javax.swing.JTextField();
        jSSalario = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaCuidadores = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        JButtonAddAnimal = new javax.swing.JToggleButton();
        JButtonEditAnimal = new javax.swing.JToggleButton();
        JButtonRemoveAnimal = new javax.swing.JToggleButton();
        JButtonErase = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        capa0.setBackground(new java.awt.Color(255, 255, 255));
        capa0.setPreferredSize(new java.awt.Dimension(800, 600));
        java.awt.GridBagLayout capa0Layout = new java.awt.GridBagLayout();
        capa0Layout.columnWidths = new int[] {0, 35, 0, 35, 0};
        capa0Layout.rowHeights = new int[] {0, 32, 0, 32, 0, 32, 0, 32, 0, 32, 0, 32, 0};
        capa0.setLayout(capa0Layout);

        addCuidador.setBackground(new java.awt.Color(255, 255, 255));
        addCuidador.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        addCuidador.setForeground(new java.awt.Color(51, 51, 51));
        addCuidador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addCuidador.setText("Añadir cuidador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        capa0.add(addCuidador, gridBagConstraints);

        JLNombre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        JLNombre.setForeground(new java.awt.Color(0, 153, 51));
        JLNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLNombre.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        capa0.add(JLNombre, gridBagConstraints);

        jTFNombreCuidador.setBackground(new java.awt.Color(255, 255, 255));
        jTFNombreCuidador.setForeground(new java.awt.Color(0, 0, 0));
        jTFNombreCuidador.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jTFNombreCuidador.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        capa0.add(jTFNombreCuidador, gridBagConstraints);

        JLSalario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        JLSalario.setForeground(new java.awt.Color(0, 153, 51));
        JLSalario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLSalario.setText("Salario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        capa0.add(JLSalario, gridBagConstraints);

        jTFTel.setBackground(new java.awt.Color(255, 255, 255));
        jTFTel.setForeground(new java.awt.Color(0, 0, 0));
        jTFTel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jTFTel.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        capa0.add(jTFTel, gridBagConstraints);

        JLEspecialidad.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        JLEspecialidad.setForeground(new java.awt.Color(0, 153, 51));
        JLEspecialidad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLEspecialidad.setText("Especialidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        capa0.add(JLEspecialidad, gridBagConstraints);

        JLNum1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        JLNum1.setForeground(new java.awt.Color(0, 153, 51));
        JLNum1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLNum1.setText("Telefono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        capa0.add(JLNum1, gridBagConstraints);

        jComboBoxEspecialidad.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        capa0.add(jComboBoxEspecialidad, gridBagConstraints);

        JLApellidos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        JLApellidos.setForeground(new java.awt.Color(0, 153, 51));
        JLApellidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLApellidos.setText("Apellidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        capa0.add(JLApellidos, gridBagConstraints);

        jTFApe.setBackground(new java.awt.Color(255, 255, 255));
        jTFApe.setForeground(new java.awt.Color(0, 0, 0));
        jTFApe.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jTFApe.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        capa0.add(jTFApe, gridBagConstraints);

        jSSalario.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));
        jSSalario.setPreferredSize(new java.awt.Dimension(100, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        capa0.add(jSSalario, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTablaCuidadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Apellidos", "Salario", "Telefono", "Especialidad", "Última Modificación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablaCuidadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                click(evt);
            }
        });
        jScrollPane1.setViewportView(jTablaCuidadores);
        if (jTablaCuidadores.getColumnModel().getColumnCount() > 0) {
            jTablaCuidadores.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTablaCuidadores.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTablaCuidadores.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTablaCuidadores.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTablaCuidadores.getColumnModel().getColumn(4).setPreferredWidth(80);
            jTablaCuidadores.getColumnModel().getColumn(5).setPreferredWidth(90);
            jTablaCuidadores.getColumnModel().getColumn(6).setPreferredWidth(150);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        JButtonAddAnimal.setBackground(new java.awt.Color(51, 51, 51));
        JButtonAddAnimal.setForeground(new java.awt.Color(0, 0, 0));
        JButtonAddAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        JButtonAddAnimal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonAddAnimal.setPreferredSize(new java.awt.Dimension(70, 22));
        JButtonAddAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAddAnimalActionPerformed(evt);
            }
        });
        jToolBar1.add(JButtonAddAnimal);

        JButtonEditAnimal.setBackground(new java.awt.Color(51, 51, 51));
        JButtonEditAnimal.setForeground(new java.awt.Color(0, 0, 0));
        JButtonEditAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        JButtonEditAnimal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonEditAnimal.setPreferredSize(new java.awt.Dimension(70, 22));
        JButtonEditAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonEditAnimalActionPerformed(evt);
            }
        });
        jToolBar1.add(JButtonEditAnimal);

        JButtonRemoveAnimal.setBackground(new java.awt.Color(51, 51, 51));
        JButtonRemoveAnimal.setForeground(new java.awt.Color(0, 0, 0));
        JButtonRemoveAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        JButtonRemoveAnimal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonRemoveAnimal.setPreferredSize(new java.awt.Dimension(70, 22));
        JButtonRemoveAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonRemoveAnimalActionPerformed(evt);
            }
        });
        jToolBar1.add(JButtonRemoveAnimal);

        JButtonErase.setBackground(new java.awt.Color(51, 51, 51));
        JButtonErase.setForeground(new java.awt.Color(0, 0, 0));
        JButtonErase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/erase.png"))); // NOI18N
        JButtonErase.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonErase.setFocusable(false);
        JButtonErase.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JButtonErase.setPreferredSize(new java.awt.Dimension(70, 22));
        JButtonErase.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JButtonErase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonEraseActionPerformed(evt);
            }
        });
        jToolBar1.add(JButtonErase);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(capa0, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(capa0, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonAddAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAddAnimalActionPerformed
        String nombre = jTFNombreCuidador.getText();
        String ape = jTFApe.getText();
        float salario = (float)jSSalario.getValue();
        String num = jTFTel.getText();
        Especialidad esp = new Especialidad((Especialidad)jComboBoxEspecialidad.getSelectedItem());
        int especialidad = esp.getId();
        if(nombre.equals("")){
            JOptionPane.showMessageDialog(null, "Introduce el nombre");
        }
        else if(ape.equals("")){
            JOptionPane.showMessageDialog(null, "Introduce el apellido");
        }
        else if(salario==0){
            JOptionPane.showMessageDialog(null, "El salario no puede ser 0");
        }
        else if(num.equals("")){
            JOptionPane.showMessageDialog(null, "Introduce el número de teléfono");
        }
        else if(num.length()!=9){
            JOptionPane.showMessageDialog(null, "Introduce correctamente número de teléfono");
        }
        else{
            try {
                String consulta = "SELECT * FROM persona,cuidador WHERE nombre='"+nombre+"' AND apellido='"+ape+"' AND TELEFONO ='"+num+"'AND CUIDADOR.ID_ESP='"+esp.getId()+"'";
                ResultSet rs1 =miConexion.comprobarDatos(consulta);
                //System.out.println(consulta);
                if(rs1==null){
                    LocalDateTime dateTime = LocalDateTime.now();
                    String currentTimeStamp = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.0").format(dateTime);
                    ResultSet rs = miConexion.getSelect("Select * from persona");
                    //Irse a la ultima linea de la tabla persona
                    rs.moveToInsertRow();
                    rs.updateString("nombre",nombre);
                    rs.updateString("apellido",ape);
                    rs.updateFloat("salario",salario);
                    rs.updateString("telefono", num);
                    rs.insertRow();
                    ResultSet rs2 = miConexion.getSelect("Select * from cuidador");
                    ResultSet getId=miConexion.comprobarDatos("SELECT AUTO_INCREMENT FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='ZOO' AND TABLE_NAME='PERSONA'");
                    //System.out.println(getId.getInt("AUTO_INCREMENT")-1);
                    rs2.moveToInsertRow();
                    rs2.updateInt(1, getId.getInt("AUTO_INCREMENT")-1);
                    rs2.updateInt(2,especialidad);
                    rs2.insertRow();
                    JOptionPane.showMessageDialog(null, "Cuidador añadido correctamente");
                    jTFNombreCuidador.setText("");
                    jTFApe.setText("");
                    jTFTel.setText("");
                    jSSalario.setValue(0);
                    modelo.addRow(new Object[] {getId.getInt("AUTO_INCREMENT")-1,nombre,ape,salario,num,esp,currentTimeStamp});
                }
                else{
                    JOptionPane.showMessageDialog(null, "El cuiador ya existe");
                }
            
        }   catch (SQLException ex) {
                Logger.getLogger(addCuidadores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_JButtonAddAnimalActionPerformed

    private void JButtonEditAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonEditAnimalActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Estás seguro? No podrás recuperar los datos anteriores","Editar cuidador",JOptionPane.YES_OPTION);
        if(resp==0){
            int fila = jTablaCuidadores.getSelectedRow();
            int id=(int)jTablaCuidadores.getValueAt(fila, 0);
            String nombre = jTFNombreCuidador.getText();
            String ape = jTFApe.getText();
            float salario = (float)jSSalario.getValue();
            String num = jTFTel.getText();
            String sentencia = "UPDATE PERSONA SET NOMBRE='"+nombre+"', APELLIDO='"+ape+"',SALARIO="+salario+",TELEFONO='"+num+"'  WHERE ID_PERSONA="+id;
            System.out.println(sentencia);
            if(miConexion.editTable(sentencia)==1){
                LocalDateTime dateTime = LocalDateTime.now();
                String currentTimeStamp = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.0").format(dateTime);
                modelo.setValueAt(jTFNombreCuidador.getText(), fila, 1);
                modelo.setValueAt(jTFApe.getText(), fila, 2);
                modelo.setValueAt(jSSalario.getValue(), fila, 3);
                modelo.setValueAt(jTFTel.getText(), fila, 4);
                modelo.setValueAt(currentTimeStamp, fila, 6);
                JOptionPane.showMessageDialog(null, "Cuidador editado correctamente");
                jTFNombreCuidador.setText("");
                jTFNombreCuidador.setText("");
                jTFTel.setText("");
                jSSalario.setValue(0);
            }
            else{
                JOptionPane.showMessageDialog(null, "Error al editar el cuidador");
            }
        }
    }//GEN-LAST:event_JButtonEditAnimalActionPerformed

    private void JButtonRemoveAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonRemoveAnimalActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Estás seguro? No vas a poder recuperar los datos eliminados","Eliminar cuidador",JOptionPane.YES_OPTION);
        if(resp==0){
            int id=(int)jTablaCuidadores.getValueAt(jTablaCuidadores.getSelectedRow(), 0);
            int fila = jTablaCuidadores.getSelectedRow();
            String sentencia1 = "DELETE FROM CUIDADOR WHERE id_per="+id;
            String sentencia2 = "DELETE FROM PERSONA WHERE ID_PERSONA="+id;
            
            //System.out.println(sentencia1);
            if(miConexion.editTable(sentencia1)==1){
                if(miConexion.editTable(sentencia2)==1){
                modelo.removeRow(fila);
                JOptionPane.showMessageDialog(null, "Cuidador elimado correctamente");
                jTFNombreCuidador.setText("");
                jTFApe.setText("");
                jTFTel.setText("");
                jSSalario.setValue(0);
                }
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Error al eliminar el cuidador");
            }
        }
    }//GEN-LAST:event_JButtonRemoveAnimalActionPerformed

    private void click(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_click
        int fila = jTablaCuidadores.getSelectedRow();
        jTFNombreCuidador.setText((String)jTablaCuidadores.getValueAt(fila,1));
        jTFApe.setText((String)jTablaCuidadores.getValueAt(fila,2));
        jSSalario.setValue((Float)jTablaCuidadores.getValueAt(fila,3));
        jTFTel.setText((String)jTablaCuidadores.getValueAt(fila,4));
        Especialidad esp = new Especialidad ((Especialidad)jTablaCuidadores.getValueAt(fila, 5));
        //System.out.println(esp.getId());
        jComboBoxEspecialidad.getModel().setSelectedItem(esp);
    }//GEN-LAST:event_click

    private void JButtonEraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonEraseActionPerformed
        jTFNombreCuidador.setText("");
        jTFApe.setText("");
        jTFTel.setText("");
        jSSalario.setValue(0);
    }//GEN-LAST:event_JButtonEraseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCuidadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCuidadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCuidadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCuidadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addCuidadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton JButtonAddAnimal;
    private javax.swing.JToggleButton JButtonEditAnimal;
    private javax.swing.JToggleButton JButtonErase;
    private javax.swing.JToggleButton JButtonRemoveAnimal;
    private javax.swing.JLabel JLApellidos;
    private javax.swing.JLabel JLEspecialidad;
    private javax.swing.JLabel JLNombre;
    private javax.swing.JLabel JLNum1;
    private javax.swing.JLabel JLSalario;
    private javax.swing.JLabel addCuidador;
    private javax.swing.JPanel capa0;
    private javax.swing.JComboBox<String> jComboBoxEspecialidad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSSalario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFApe;
    private javax.swing.JTextField jTFNombreCuidador;
    private javax.swing.JTextField jTFTel;
    private javax.swing.JTable jTablaCuidadores;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
