/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazV2;
import java.awt.Cursor;
import static java.awt.Frame.HAND_CURSOR;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import util.TextPrompt;

/**
 *
 * @author dam2
 */
public class addEspecie extends javax.swing.JFrame {
    Connection miConexion;
    DefaultTableModel modelo;
    /**
     * Creates new form addEspecie
     */
    public addEspecie() {
        initComponents();
        JButtonAddEspecie.setCursor(new Cursor(HAND_CURSOR));
        JButtonEditEspecie.setCursor(new Cursor(HAND_CURSOR));
        JButtonErase.setCursor(new Cursor(HAND_CURSOR));
        //TextPrompt sirve para poner un placeholder en un textfield
        TextPrompt name = new TextPrompt("Monos", jTNombreEspecie);
            
        miConexion = new Conexion("localhost","3306","zoo","zoologico","pepe").makeConnect();
        modelo = (DefaultTableModel) jTablaEspecies.getModel();
            String consulta = "SELECT * FROM ESPECIE";
            ResultSet rsTabla = util.Conexion.getSelect(consulta,miConexion);
        try {
            while(rsTabla.next()){
                modelo.addRow(new Object[] {rsTabla.getInt(1),rsTabla.getString(2)});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar los datos");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaEspecies = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        LnombreEspecie = new javax.swing.JLabel();
        jTNombreEspecie = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        JButtonAddEspecie = new javax.swing.JToggleButton();
        JButtonEditEspecie = new javax.swing.JToggleButton();
        JButtonErase = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTablaEspecies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablaEspecies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEspecie.this.mouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablaEspecies);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 400));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 15, 0, 15, 0};
        jPanel2Layout.rowHeights = new int[] {0, 25, 0, 25, 0};
        jPanel2.setLayout(jPanel2Layout);

        LnombreEspecie.setFont(new java.awt.Font("Freshman", 0, 18)); // NOI18N
        LnombreEspecie.setForeground(new java.awt.Color(0, 86, 44));
        LnombreEspecie.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(LnombreEspecie, gridBagConstraints);

        jTNombreEspecie.setBackground(new java.awt.Color(255, 255, 255));
        jTNombreEspecie.setFont(new java.awt.Font("Freshman", 0, 18)); // NOI18N
        jTNombreEspecie.setForeground(new java.awt.Color(0, 0, 0));
        jTNombreEspecie.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(0, 102, 51))); // NOI18N
        jTNombreEspecie.setPreferredSize(new java.awt.Dimension(100, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jTNombreEspecie, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Freshman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Especies");
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(jLabel1, gridBagConstraints);

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        JButtonAddEspecie.setBackground(new java.awt.Color(51, 51, 51));
        JButtonAddEspecie.setForeground(new java.awt.Color(0, 0, 0));
        JButtonAddEspecie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        JButtonAddEspecie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonAddEspecie.setPreferredSize(new java.awt.Dimension(70, 22));
        JButtonAddEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAddEspecieActionPerformed(evt);
            }
        });
        jToolBar1.add(JButtonAddEspecie);

        JButtonEditEspecie.setBackground(new java.awt.Color(51, 51, 51));
        JButtonEditEspecie.setForeground(new java.awt.Color(0, 0, 0));
        JButtonEditEspecie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        JButtonEditEspecie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonEditEspecie.setPreferredSize(new java.awt.Dimension(70, 22));
        JButtonEditEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonEditEspecieActionPerformed(evt);
            }
        });
        jToolBar1.add(JButtonEditEspecie);

        JButtonErase.setBackground(new java.awt.Color(51, 51, 51));
        JButtonErase.setForeground(new java.awt.Color(0, 0, 0));
        JButtonErase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/erase.png"))); // NOI18N
        JButtonErase.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonErase.setFocusable(false);
        JButtonErase.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JButtonErase.setPreferredSize(new java.awt.Dimension(70, 22));
        JButtonErase.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JButtonErase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonEraseActionPerformed(evt);
            }
        });
        jToolBar1.add(JButtonErase);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonAddEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAddEspecieActionPerformed
        String especie = jTNombreEspecie.getText();
        if(especie.equals("")){
            JOptionPane.showMessageDialog(null, "Introduce la especie");
        }
        else{
            try {
                String consulta = "SELECT * FROM especie WHERE NOMBRE_ESPECIE='"+especie+"'";
                ResultSet rs1 = util.Conexion.comprobarDatos(consulta,miConexion);
                if(rs1==null){
                    ResultSet rs = util.Conexion.getSelect(consulta,miConexion);
                    //Irse a la ultima linea de la tabla
                    rs.moveToInsertRow();
                    rs.updateString("nombre_especie",especie);
                    rs.insertRow();
                    ResultSet getId= util.Conexion.comprobarDatos("SELECT AUTO_INCREMENT FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='ZOO' AND TABLE_NAME='ESPECIE'",miConexion);
                    JOptionPane.showMessageDialog(null, "Especie añadida correctamente");
                    jTNombreEspecie.setText("");
                    modelo.addRow(new Object[] {getId.getInt("AUTO_INCREMENT")-1,especie});

                }
                else{
                    JOptionPane.showMessageDialog(null, "La especie ya existe");
                }

            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(addEspecie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_JButtonAddEspecieActionPerformed

    private void JButtonEditEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonEditEspecieActionPerformed
        try{
            int resp = JOptionPane.showConfirmDialog(null, "¿Estás seguro? No podrás recuperar los datos anteriores","Editar especie",JOptionPane.YES_OPTION);
            if(resp==0){
                String nombre = jTNombreEspecie.getText();
                int fila = jTablaEspecies.getSelectedRow();
                int id=(int)jTablaEspecies.getValueAt(fila, 0);
                String sentencia = "UPDATE ESPECIE SET NOMBRE_ESPECIE='"+nombre+"' WHERE ID_ESPECIE="+id;
                if(util.Conexion.editTable(sentencia,miConexion)==1){
                    modelo.setValueAt(jTNombreEspecie.getText(), fila, 1);
                    JOptionPane.showMessageDialog(null, "Especie editada correctamente");
                    jTNombreEspecie.setText("");
                }
                else{
                    JOptionPane.showMessageDialog(null, "Error al editar la especie");
                }
            }
        }
        catch(java.lang.NullPointerException ex){
            JOptionPane.showMessageDialog(null, "Selecciona una fila de la tabla");
        }
    }//GEN-LAST:event_JButtonEditEspecieActionPerformed

    private void mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClicked
        int fila = jTablaEspecies.getSelectedRow();
        jTNombreEspecie.setText((String)jTablaEspecies.getValueAt(fila,1));
    }//GEN-LAST:event_mouseClicked

    private void JButtonEraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonEraseActionPerformed
        jTNombreEspecie.setText("");
    }//GEN-LAST:event_JButtonEraseActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton JButtonAddEspecie;
    private javax.swing.JToggleButton JButtonEditEspecie;
    private javax.swing.JToggleButton JButtonErase;
    private javax.swing.JLabel LnombreEspecie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTNombreEspecie;
    private javax.swing.JTable jTablaEspecies;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
