/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazV2;

import java.awt.Cursor;
import static java.awt.Frame.HAND_CURSOR;

/**
 *
 * @author Sergio
 */
public class menuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form menuPrincipalñ
     */
    public menuAdmin() {
        initComponents();
        jButtonAnimales.setCursor(new Cursor(HAND_CURSOR));
        jButtonCuidados.setCursor(new Cursor(HAND_CURSOR));
        jButtonEspecialidad.setCursor(new Cursor(HAND_CURSOR));
        jButtonEspecie.setCursor(new Cursor(HAND_CURSOR));
        jButtonCuidadores.setCursor(new Cursor(HAND_CURSOR));
        jButtonTareas.setCursor(new Cursor(HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonAnimales = new javax.swing.JButton();
        jButtonCuidadores = new javax.swing.JButton();
        jButtonCuidados = new javax.swing.JButton();
        jButtonEspecialidad = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonTareas = new javax.swing.JButton();
        jButtonEspecie = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(279, 74));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 50, 0, 50, 0};
        jPanel2Layout.rowHeights = new int[] {0, 25, 0, 25, 0};
        jPanel2.setLayout(jPanel2Layout);

        jLabel1.setFont(new java.awt.Font("Freshman", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 86, 44));
        jLabel1.setText("Main Menu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        jPanel2.add(jLabel1, gridBagConstraints);

        jButtonAnimales.setFont(new java.awt.Font("Freshman", 0, 12)); // NOI18N
        jButtonAnimales.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAnimales.setText("Animales");
        jButtonAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnimalesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jButtonAnimales, gridBagConstraints);

        jButtonCuidadores.setFont(new java.awt.Font("Freshman", 0, 12)); // NOI18N
        jButtonCuidadores.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCuidadores.setText("Cuidadores");
        jButtonCuidadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuidadoresActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jButtonCuidadores, gridBagConstraints);

        jButtonCuidados.setFont(new java.awt.Font("Freshman", 0, 12)); // NOI18N
        jButtonCuidados.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCuidados.setText("Cuidados");
        jButtonCuidados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuidadosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jButtonCuidados, gridBagConstraints);

        jButtonEspecialidad.setFont(new java.awt.Font("Freshman", 0, 12)); // NOI18N
        jButtonEspecialidad.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEspecialidad.setText("Especialidad");
        jButtonEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEspecialidadActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jButtonEspecialidad, gridBagConstraints);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jLabel2, gridBagConstraints);

        jButtonTareas.setFont(new java.awt.Font("Freshman", 0, 12)); // NOI18N
        jButtonTareas.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTareas.setText("Tareas");
        jButtonTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTareasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jButtonTareas, gridBagConstraints);

        jButtonEspecie.setFont(new java.awt.Font("Freshman", 0, 12)); // NOI18N
        jButtonEspecie.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEspecie.setText("Especies");
        jButtonEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEspecieActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jButtonEspecie, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(297, 336));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/zoologico.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnimalesActionPerformed
        addAnimal OpenAnimal = new addAnimal(true);
        OpenAnimal.setVisible(true);
    }//GEN-LAST:event_jButtonAnimalesActionPerformed

    private void jButtonCuidadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuidadoresActionPerformed
        addCuidadores OpenCuidadores = new addCuidadores();
        OpenCuidadores.setVisible(true);
    }//GEN-LAST:event_jButtonCuidadoresActionPerformed

    private void jButtonCuidadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuidadosActionPerformed
        addCuidados OpenCuidados = new addCuidados(true);
        OpenCuidados.setVisible(true);
    }//GEN-LAST:event_jButtonCuidadosActionPerformed

    private void jButtonEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEspecialidadActionPerformed
        addEspecialidad OpenEspecialidad = new addEspecialidad();
        OpenEspecialidad.setVisible(true);
    }//GEN-LAST:event_jButtonEspecialidadActionPerformed

    private void jButtonTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTareasActionPerformed
        Actividades OpenActividades = new Actividades(-1,"admin",true);
        OpenActividades.setVisible(true);
    }//GEN-LAST:event_jButtonTareasActionPerformed

    private void jButtonEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEspecieActionPerformed
        addEspecie OpenEspecie = new addEspecie();
        OpenEspecie.setVisible(true);
    }//GEN-LAST:event_jButtonEspecieActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnimales;
    private javax.swing.JButton jButtonCuidadores;
    private javax.swing.JButton jButtonCuidados;
    private javax.swing.JButton jButtonEspecialidad;
    private javax.swing.JButton jButtonEspecie;
    private javax.swing.JButton jButtonTareas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
